### ISSUE TITLE
Add support for numerical sorting

### ISSUE THREAD

**Issue by xX420MCplayerXx** [86Box/86BoxManager#125] opened 2024-03-02 17:07 UTC
**Describe the bug**
When you have 9 VMs labled 1-9 and you ad a 10th one, the 10th one will be uner the 1st one and not the 9th one.

**To Reproduce**
1. Create 9 VMs labled 1-9.
2. Create a 10th labled 10
3. You will see that the 10th one is under the 1st one and not the 9th one.

**Expected behavior**
What I expected to happen is the 10th one is placed under the 9th one.

**Screenshots**
![image](https://github.com/86Box/86BoxManager/assets/102683266/2a10e3c8-4a8e-4732-8144-0cf391c0cb57)

**Environment (please complete the following information):**
 - Host OS: Windows 10 Pro 22H2 OS Build 19045.4046
 - 86Box build 4311 regular
 - 86Box Manager Version 1.7.4

**Additional context**
I like ordering my VMs, so this annoys me.

**Comment by nanitaro** [comment] 2024-04-15 09:00
This is the result of sorting by name correctly.
1.->10 -> 2.->3.->...
No problem.
The solution is to make the labels two-digit.
01.->02.->03.->.... .10.

**Comment by dhrdlicka** [comment] 2024-04-19 09:46
The sort technically works as intended, it's just that the ASCII code for a dot is lower than the ASCII code for digits. Not really a bug, so I am marking this as an enhancement instead.

**Comment by daviunic** [comment] 2024-11-17 18:52
Would need to look into this to see how much effort it would be, but probably not worth it.

**Closed by daviunic** 2024-11-17 18:52 UTC
Labels: enhancement

**Comment by milnak** [comment] 2025-01-23 16:50
FYI: https://stackoverflow.com/questions/248603/natural-sort-order-in-c-sharp
