### ISSUE TITLE
Settings not saving if only modifying a text field and logging disabled

### ISSUE THREAD

**Issue by eggleston1** [86Box/86BoxManager#62] opened 2019-08-24 06:07 UTC
I discovered this bug while trying to change the path to 86Box and the VM directory. If I change either path I noticed the Apply button is still disabled and by pressing OK the Settings window closes but the changes aren't updated in the registry.

Fields that are impacted:
- 86Box path (General)
- VM path (General)
- Launch timeout field (Advanced)

**Temporary Workaround** _(must do this each time Settings are opened or applied)_
- Open Settings
- Change paths/launch timeout
- Toggle any checkbox on either tab
- Press "OK" or "Apply"

**Permanent Workaround**
- Open Settings
- Select "Advanced" tab
- Check "Enable 86Box logging to file"
- Input any text
- Uncheck "Enable 86Box logging to file"
- Press "OK" or "Apply"

If you are utilizing the logging feature then you won't encounter this bug. As long as some text is in the log file text field all settings modified will be saved.

**Comment by daviunic** [comment] 2019-08-24 09:08
Confirmed in 1.5.2, will be fixed.

**Comment by daviunic** [comment] 2019-08-24 09:56
Fixed in 1.5.4. It was an empty string check on txtLogPath causing the issue, since the state of cbxLoggingEnabled was not considered for this check. I've reworked the code a bit so this is fixed and that a warning is displayed if you try to use an empty or whitespace string for the log path. The 86Box.exe not found warning has also been improved.

**Closed by daviunic** 2019-08-24 09:56 UTC
Labels: bug
