### ISSUE TITLE
86Box Manager does not save any new profile created

### ISSUE THREAD

**Issue by Fenix770** [86Box/86BoxManager#100] opened 2021-11-10 21:37 UTC
**Describe the bug**
When I create a new profile, 86box Manager does not save the configuration. 86box Dev version 3.0.0.3249 works fine. I suspect this bug appeared on 3.0.0.3250 or later commits of 86box.

**To Reproduce**
1. Simply try to create a new profile with the last commit of 86box Dev.
2. Check to see that the config is not saved.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - 86Box version:  3.0.0.3249
 - Build type: Dev

**Comment by OBattler** [comment] 2021-11-10 21:50
Transferred the issue to 86BoxManager, because it's the Manager that has seemingly become incompatible with later 86Box builds.

**Comment by daviunic** [comment] 2021-11-11 19:03
I can't reproduce this problem with Manager 1.7.2 and 86Box dev build 3255, so I'm gonna need more info.

- Does it work fine if you try launching 86Box manually with the -P argument and the config path?
- Have you tried the regular build?
- Can you post the full path to where the config is supposed to be saved?
- Have you tried saving the config to any other folder?

**Closed** 2022-02-16 19:24 UTC
